
services:
  fit-training:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /home/mambauser/course
      - type: volume
        source: week1_data
        target: /home/mambauser/course/week1/data
      - type: bind
        source: "${HOME}/.docker_bash_history"
        target: /home/mambauser/.bash_history
      - type: bind
        source: "${HOME}/.gitconfig"
        target: /home/mambauser/.gitconfig
        read_only: true
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
      # - WANDB_API_KEY=${WANDB_API_KEY}
      # - WANDB_PROJECT=${WANDB_PROJECT:-fit-course}

## TODO postponed for now
#  label-studio:
#    image: label-studio:latest
#    ports:
#      - "127.0.0.1:8080:8080"
#    volumes:
#      - type: volume
#        source: label_studio_data
#        target: /label-studio/data
#    environment:
#      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
#      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/data/media

volumes:
  week1_data:
  label_studio_data:
